# Generated by Django 2.2.5 on 2019-12-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='title',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Tumblr', 'Tumblr')], max_length=255),
        ),
    ]
